### ISSUE TITLE
Bug appel API

### ISSUE THREAD

**Issue by bennijamm** [Aohzan/ipx800#13]
Bonjour,
Je m'apprête à basculer de Jeedom à Home Assistant et je suis en train de refaire mes scénarios avec Node-Red.

Quand je lancer un cover_open ou cover_close, j'obtiens cette erreur :
"Call-service API error.  Error Message: ('IPX800 api request error, url: %s`r%s', 'http://10.0.4.200:80/api/xdevices.json?key=removed&SetVR05=100', {'product': 'IPX800_V4', 'status': 'Error'})"

Pour autant l'action se réalise bien, d'où ce message...
Quand j'essaie de passer cette même commande (en remplaçant l'apikey), ça passe sans erreur.
Je ne sais pas si ça peut avoir une relation, j'ai fixé le scan_interval à 2.

Merci

**Comment by Aohzan** [comment]
bonjour,
est-ce que la commande est bien lancée qu'une seule fois ?

**Comment by bennijamm** [comment]
Bonjour,
J'utilise un groupe de 3 entités. Est-ce que ça peut être lié ?
Quand j'envoie l'instruction aux 3 entités séparément, pas d'erreur. Quand je passe par le groupe, les instructions sont bien envoyée mais je reçois cette fameuse erreur...

**Comment by Aohzan** [comment]
J'ai ça quand je demande d'éteindre toutes les lumières, ça marche bien, mais il y a toujours une erreur d'API. J'ai vu que l'IPX renvoi parfois une erreur sur son API mais que la commande est bien prise en compte :/

**Comment by bennijamm** [comment]
Après quelques jours, je constate toujours des erreurs même sur les envois individuels...
J'ai fixé le temps de refresh à 2 secondes et j'ai coupé le jeedom qui l'interrogeait aussi mais ça n'a rien changé.

**Comment by Aohzan** [comment]
Corrigé dans la prochaine version
Je trouve que 2s est trop rapide perso, je descends pas en dessous des 15 secondes de mon côté pour ne pas trop solliciter l'ipx comme GCE l'indique

**Comment by bennijamm** [comment]
Merci. 
je ne connaissais pas la technique du push mais je vais l’utiliser. C’est pour cela que j’avais réglé un délai très court, pour avec des triggers performants.
