### ISSUE TITLE
Nouvelle version sans erreur

### ISSUE THREAD

**Issue by bennijamm** [Aohzan/ipx800#16]
Bonjour,
La nouvelle version qui ne génère plus d'erreur sera-t-elle bientôt disponible.
J'ai tous les jours des groupes de volets ou de lampes qui ne fonctionnent pas correctement...
Merci :)

**Comment by Aohzan** [comment]
Tu peux utiliser la version sur la branche dev : https://github.com/Aohzan/ipx800/tree/dev
elle fonctionne bien, je devrais la passer en stable bientôt

**Comment by bennijamm** [comment]
j'ai tenté de l'installé, mais ça m'a dupliqué toutes les entités.
Le "ipx800" est devenu "ipx800 v4", normal ?
Est-ce possible de corriger cela pour ne pas avoir à remapper toutes mes entités dans les scénarios ?
Merci

**Comment by Aohzan** [comment]
Oui c'est normal c'est pour différencier les différentes versions d'IPX
Normalement ça ne change rien au nommage des entités qui est fait automatiquement par home assistant d'après le `name` donné. Par contre pour ne pas avoir de `(2)` derrièrepar exemple,il faut retirer l'ancienne version, restart,vérifier que toutes les entitéssont bien supprimées puis mettre le nouveau `ipx800v4:`
