### ISSUE TITLE
Mettre à jour tous les binary sensor via push

### ISSUE THREAD

**Issue by bennijamm** [Aohzan/ipx800#18]
Bonjour,
J'ai défini une fréquence d'actualisation du 1 sec. Je sais que c'est très court mais j'en ai besoin car beaucoup de capteurs (ouverture de portes, mouvements,...) qui me servent de déclencheurs. Je ne me vois pas créer un scénario dans l'IPX pour chaque  relai concerné. 
Y a t il une autre solution ?
Merci !

**Comment by Aohzan** [comment]
Bonjour,
Tu peux faire un push pour plusieurs entités : https://github.com/Aohzan/ipx800/tree/dev#push-data-from-the-ipx800

**Comment by bennijamm** [comment]
Est-ce qu'il te serait envisageable de mettre à jour toutes les entrées de même type sur un seul push comme le propose le plugin de Jeedom par ex. Voici un extrait de la doc : 

`
Push des informations de l’IPX vers Jeedom
Pour eviter de faire un refresh des informations dans Jeedom ou des interogations trop fréquente (qui peuvent mettre à mal l’ipx800) il est possible de demande à l’IPX800 de pousser les informations vers Jeedom (attention ce n’est pas possible pour tous les types d’entrée/sortie)

Voici la syntaxe à utiliser dans un push IPX pour :

Mise à jour de toutes les entrées digitales : /core/api/jeeApi.php?type=ipx800v4&apikey=XXX&typeData=allD&data=$D
Mise à jour de tous les relais : /core/api/jeeApi.php?type=ipx800v4&apikey=XXX&typeData=allR&data=$R
Mise à jour de toutes les sorties virtuelles : /core/api/jeeApi.php?type=ipx800v4&apikey=XXX&typeData=allVO&data=$VO
Mise à jour d’une seule variable : /core/api/jeeApi.php?type=ipx800v4&apikey=XXX&typeData=A&data=$B avec A qui prend les valeurs D, R ou VO et B qui prend la référence de la valeur à envoyer sur l’IPX(par exemple D1 ou VO1 ou R1…)
Ensuite il vous faire une scene par type (entrée, relais…) avec :

Evenement : ON EVENT et choisir le type voulu (par exemple Sorties physiques)
Action : ON
Résultat : PUSH et choisir le push correspondant (par exemple Jeedom Relais)
`

Cette solution apporterait vraiment une simplicité de déploiement ! (je suis conscient que c'est un investissement en temps aussi...)
Merci.
