### ISSUE TITLE
Interprétation retour push

### ISSUE THREAD

**Issue by bennijamm** [Aohzan/ipx800#19]
Bonjour,
C'est encore moi :) J'a commencé à configurer le push pour éviter d'appeler toutes les secondes l'état de toutes les entrées/sorties de l'IPX... je progresse ;).
Le problème du moment c'est la gestion des XDIMMER et des X4VR.
Je pense que l'API retourne une valeur qui correspond soit au 0% d'éclairage ou au % d'ouverture du volet. Dans ton code, pour ce que j'en ai compris, tu alimentes le state avec on ou off. Et du coup, le push ne fonctionne pas...
Est-ce que tu penses que tu pourrais tenir compte des vraies valeurs renvoyées (comme c'est le cas avec le polling) ?
Merci

**Comment by Aohzan** [comment]
En effet je ne mets à jour que les entity qui sont à `on` ou `off`. À la base car c'est sur des switchs ou binary_sensors que tu as besoin d'avoir l'état immédiatement au changement pour déclencher un scénario
Quel est le besoin d'avoir l'état d'une lumière ou d'un volet instantannément dans Home Assistant ?

Une autre possibilité serait de faire un push pour demander à Home Assistant de rafraîchir toutes les données, ça permettrait d'avoir un temps de réaction inférieur à la seconde

**Comment by bennijamm** [comment]
La mise à jour instantanée nous est utile quand on n'a pas la vue sur le "résultat". Ex, on n'est pas à la maison, on veut ouvrir un volet à 50%, on appuie sur le bouton d'ouverture mais si on n'a pas le résultat instantanément, on n'est pas sûr que la commande a bien été prise en compte et donc que le volet est bien au niveau demandé.
Pareil pour la lumière, j'allume souvent la lumière à distance pour ma fille avec la tablette qui est à un bout de la maison. Si je n'ai pas le retour instantané, je ne peux pas donner le go à ma fille...
Autre exemple, le soir avant de me coucher, je check (et c'est bientôt une automatisation qui checkera) que toutes les lumières sont bien éteintes. Si au moment où je regarde, je ne suis pas sûr d'avoir les tous derniers états, ce n'est pas bon non plus...
Pour moi, c'est essentiel d'avoir de l'instantanéité.

Je ne vois pas comment faire un push (depuis l'IPX ? à partir de quel événement ?) pour demander à HA de rafraichir toutes les données... ? je veux bien que tu m'éclaires;... :=

**Comment by Aohzan** [comment]
Actuellement quand tu allumes une lumières, tu vois l'état allumé directement non ?

**Comment by Aohzan** [comment]
je ferme au profit de https://github.com/Aohzan/ipx800/issues/17
