### ISSUE TITLE
Mauvaise vérification de l'authentification

### ISSUE THREAD

**Issue by guigeek38** [Aohzan/ipx800#22]
Bonjour,
Il me semble qu'il y a une petite erreur sur l'authentification :
https://github.com/Aohzan/ipx800/blob/1cdb68a872f6723493a82b7399cd255f78a50f6f/custom_components/ipx800v4/__init__.py#L380

Avec cette ligne si le _username_ est bon, le mot de passe ne sera pas vérifié puisque la 1ère partie de la condition `and` est fausse. Je pense qu'il faudrait alors mettre un `or` pour que la condition soit vraiment vérifiée.

Et encore merci pour votre travail sur cette nouvelle version !

**Comment by Aohzan** [comment]
En effet merci, corrigé https://github.com/Aohzan/ipx800/commit/fb543d279fdb8b7460b973ba20fb748bd5a033d0
