### ISSUE TITLE
Compteur IPX

### ISSUE THREAD

**Issue by carfnann** [Aohzan/ipx800#26]
Hello

est il possible de récupérer les compteurs de l'IPX?
je n'ai pas trouvé le type adéquat

merci

**Comment by Aohzan** [comment]
Ce n'est pas remonté par défaut, je vais voir pour l'ajouter dans la prochaine version

**Comment by Aohzan** [comment]
@carfnann prend la dernière version et ajoute dans ton code par exemple:
```
      - component: sensor
        name: Mon compteur
        type: counter
        id: 1
```
