### ISSUE TITLE
Release 2021-12 : cannot import name 'HTTP_OK'

### ISSUE THREAD

**Issue by LHommeQuAVuLOurs** [Aohzan/ipx800#28]
Hello,
There's a new problem experienced right after the upgrade to release 2021.12 of Home Assistant.
Any feedback on this topic ? Am alone to have this problem ?

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 08:43:13 (1 occurrences)
Last logged: 08:43:13

Setup failed for ipx800v4: Unable to import component: cannot import name 'HTTP_OK' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Thank you for your help 

Simon

**Comment by Aohzan** [comment]
Hello,
You have to upgrade to the last release
