### ISSUE TITLE
problemi avvio ipx800 su homeassistant

### ISSUE THREAD

**Issue by 10051402** [Aohzan/ipx800#30]
Buonasera, non riesco ad avviare l'integreazione in home assistant.
l'errore è questo:
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.ipx800v4
Source: custom_components/ipx800v4/__init__.py:156
Integration: GCE IPX800 V4 (documentation, issues)
First occurred: 23:05:56 (4 occurrences)
Last logged: 23:06:19

Cannot connect to the IPX800 named IPX800, check host, port or api_key
Cannot connect to the IPX800 named alessandro, check host, port or api_key

Sicuramente non riesco a compilare correttamente il file configuration.yaml
potete aiutarmi nella compilazione?
i dati sono:
ipx800v4 in rete ip.192.168.1.225 porta 9800
password api: apikey  pota:9870

Grazie per l'aiuto

**Comment by Aohzan** [comment]
English please :pray:

**Comment by 10051402** [comment]
hello, I was able to connect ipx800 with the plugin but I would need to display the buttons for the 56 relays and the analog inputs in the home assistant but I don't know how to do it. can you give me a hand? thank you

**Comment by Aohzan** [comment]
You have to put this for each of the relays you want to control
```
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 30
```
and for analog inputs
```
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 1
```

**Comment by 10051402** [comment]
this is what i have to write in configuration.yamal me to view the buttons and inputs in home assistant how can i do?

**Comment by 10051402** [comment]
non così se mi puoi aiutare o a chi rivolgermi. non così alcuni mettere in home assistant i pulsanti e gli indicatori degli ingressi digitali. devo configurare qualche file?

**Comment by 10051402** [comment]
I don't know how to display 56 buttons corresponding to ipx800 and interfaces and 56 inputs in home assistant. can you help me? thank you

**Comment by Aohzan** [comment]
can you paste the ipx800v4 part of your configuration.yml please

**Comment by 10051402** [comment]
ok, I am attaching configuration.yaml.
if you can modify it as you think horrible thank you:


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Example configuration.yaml entry
ipx800v4:
  - name: IPX800
    host: 192.168.1.225
    port: 9800
    api_key: apikeys
    username: admin
    password: 250617!Alecri
    device:
      - name: Chaudière
        icon: mdi:water-boiler
        type: "relay"
        component: "switch"
        id: 3
      - name: Lumière Garage
        type: relay
        component: light
        id: 9
      - name: Lumière Salle à Manger
        type: xdimmer
        component: light
        id: 1
      - component: light
        name: Spots Cuisine
        type: xpwm
        id: 1
      - component: light
        name: "Bandeau de LED Salon"
        type: xpwm_rgbw
        ids: [9, 10, 11, 12]
        transition: 1.5
      - component: binary_sensor
        device_class: motion
        name: Présence Cuisine
        type: virtualout
        id: 1
      - component: binary_sensor
        name: Sonnette
        type: digitalin
        icon: mdi:bell-circle-outline
        id: 1
      - component: sensor
        device_class: illuminance
        name: Luminosité Cuisine
        icon: mdi:white-balance-sunny
        type: analogin
        id: 1
        unit_of_measurement: "lx"
      - component: sensor
        name: Capteur Rez-de-Chaussée
        type: xthl
        id: 1
      - component: cover
        name: Volet Salon
        type: x4vr
        ext_id: 1
        id: 1
      - component: climate
        name: Radiateur Salon
        type: x4fp
        ext_id: 1
        id: 1
      - component: climate
        name: Radiateur Salle de Bains
        type: relay
        ids: [7, 8]
      - component: sensor
        name: Compteur
        type: counter
        id: 1

**Comment by 10051402** [comment]
ok, I am attaching configuration.yaml.
if you can modify it as you think horrible thank you:


Configurare una configurazione predefinita di Home Assistant (frontend, api, ecc.)
default_config:

Sintesi vocale
tts:

piattaforma: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

Esempio di voce configuration.yaml
ipx800v4:

nome: IPX800
host: 192.168.1.225
porta: 9800
api_key: apikeys
nome utente: password amministratore
: 250617! Dispositivo Alecri
:
nome: Chaudière
icona: mdi:tipo caldaia ad
acqua: "relè"
componente: "interruttore"
id: 3
nome: Lumière Tipo
di garage: componente relè
: id luce
: 9
nome: Lumière Salle à Tipo di mangiatoia
: xdimmer
componente: id luce
: 1
componente: light
name: Spots Tipo di cucina
: xpwm
id: 1
componente: nome luce
: "Bandeau de LED Salon"
tipo: xpwm_rgbw
ids: [9, 10, 11, 12]
transizione: 1.5
componente: binary_sensor
device_class: motion
name: Présence Tipo di cucina
: virtualout
id: 1
componente:
nome binary_sensor: Sonnette
tipo: digitalin
icon: mdi:bell-circle-outline
id: 1
componente: sensore
device_class: nome illuminamento
: Luminosité Cuisine
icon: mdi:white-balance-sunny
type: analogin
id: 1
unit_of_measurement: "lx"
componente: nome sensore
: Capteur Rez-de-Chaussée
tipo: xthl
id: 1
componente: nome copertina
: Volet Tipo
salone: x4vr
ext_id: 1
id: 1
componente: nome clima
: Radiateur Tipo
salone: x4fp
ext_id: 1
id: 1
componente: nome clima
: Radiateur Salle de Bains
tipo: relè
ids: [7, 8]
componente: nome sensore
: Tipo compteur
: id contatore
: 1

**Comment by Aohzan** [comment]
when you past your configuration, delete password and put ````` before and after

**Comment by 10051402** [comment]
could you send me the correct configuration.yaml file for my settings? thank you

**Comment by 10051402** [comment]
good evening, I do not know if I have explained myself well about my problem, summarizing:
I am attaching the configuration.yaml file (if you can check it and possibly correct it I would be grateful)
Furthermore I would like to know the procedure for adding both the relays and the inputs in a visual way on the home assistant.
pending greeting and thank you

**Comment by Aohzan** [comment]
You have an example in the README, fill it with you own information, then put everything you want in the `devices` part for your relays and analog inputs

**Comment by 10051402** [comment]
good evening, I do not know if I have explained myself well about my problem, summarizing:
I am attaching the configuration.yaml file that I have configured up to 10 relays and 10 inputs (if you can check it and possibly correct it I would be grateful)
I would like to know if the two configuration examples on the ipx800 push are good for my case.
Furthermore I would like to know the procedure for adding both the relays and the inputs in a visual way on the home assistant.
pending greeting and thank you


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Example configuration.yaml entry
ipx800v4:
  - name: IPX800
    host: 192.168.1.225
    port: 9800
    api_key: apikey
    username: alessandro
    password: 250617!Alecri
    device:
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 1
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 2
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 3
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 4
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 5
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 6
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 7
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 8
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 9
      - name: My relay 30
        type: "relay"
        component: "switch"
        id: 10

      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 1
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 2
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 3
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 4
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 5
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 6
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 7
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 8
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 9
      - component: sensor
        name: My Analog Input 1
        type: analogin
        id: 10

**Comment by 10051402** [comment]
I don't know if it's possible for you but we will be able to connect with team viever and can you give me a hand?
thank you

**Comment by Aohzan** [comment]
No i don't do that
The configuration seems ok except that you put the same name

What logs errors do you have ?

**Comment by 10051402** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.ipx800v4
Source: custom_components/ipx800v4/__init__.py:176
Integration: GCE IPX800 V4 (documentation, issues)
First occurred: 15:14:33 (1 occurrences)
Last logged: 15:14:33

A scan interval too low has been set, you probably will get errors since the IPX800 can't handle too much request at the same time

**Comment by 10051402** [comment]
I have no errors I just need to know how to view the relays in the home assistant.
that's why I asked you if you could help me by connecting to my pc. if you can't do nothing.
if you could send me instructions on what to select in the home assistant to see buttons and inputs graphically.

Thank you,

**Comment by Aohzan** [comment]
https://www.home-assistant.io/dashboards/

https://www.home-assistant.io/dashboards/entity/
https://www.home-assistant.io/dashboards/button/
...

**Comment by 10051402** [comment]
thank you for your instructions but i can't add buttons and inputs on home assistant. I was wondering if you could connect with me on tean viewer to show me at least one button and one input put on the home assistant interface but if you can't thanks anyway. I know that I will abandon it because I am not capable

**Comment by Aohzan** [comment]
I don't do Home-Assistant basic support, please watch documentation or youtube videos

**Comment by 10051402** [comment]
good evening, I managed to get the home assistant to recognize the ipx800 card.
but in the states I find an off update.gce_ipx800_v4
It's regular?
In the configuration in devices and services I find GCE IPX800 V4
and selecting it tells me on the item you check that this device has no entity; must he have them?

**Comment by 10051402** [comment]
good evening, I managed to get the home assistant to recognize the ipx800 card.
but in the states I find an off update.gce_ipx800_v4
It's regular?
In the configuration in devices and services I find GCE IPX800 V4
and selecting it tells me on the item you check that this device has no entity; must he have them?

**Comment by Aohzan** [comment]
yes, check logs

**Comment by 10051402** [comment]
where can I find the logs?

**Comment by 10051402** [comment]
in logs tells me gce ipx800 v4 off
yet the card is plugged in and turned on. what should I do?
