### ISSUE TITLE
Integration Enocean - X-ENO

### ISSUE THREAD

**Issue by vx4500** [Aohzan/ipx800#34]

**Comment by Aohzan** [comment]
c'est pour la v4 ou la v5 ?

**Comment by Aohzan** [comment]
pour la 5, je ne vois pas d'API pour piloter https://v5.gce-electronics.com/?CAT=api

**Comment by vx4500** [comment]
Pour la V4

**Comment by Aohzan** [comment]
ça représente pas mal de boulot, je vais voir si je trouve le temps

**Comment by talos-sail** [comment]
Bonjour,
Avez-vous avancé sur l'integration X-ENO ?
Je possede pas mal de modules sondes temp/hum et prises avec consommation.
Merci

**Comment by Aohzan** [comment]
C'est assez compliqué de développer sans avoir les modules de son côté pour valider en diret...

**Comment by ydubreuil** [comment]
J'ai fait une PR avec le support pour les capteurs https://github.com/Aohzan/ipx800/pull/49

**Comment by Aohzan** [comment]
Merci @ydubreuil , dispo en 3.7.0
