### ISSUE TITLE
IPX800-v4 HACS Integration - Unknown error

### ISSUE THREAD

**Issue by DOMNA13** [Aohzan/ipx800#36]
Bonjour, 
Le lien HACS pour l'IPX800-V4 remonte une erreur inconnue, est-il possible de m'aider svp ? 
Merci

**Comment by Aohzan** [comment]
Bonjour
Il faudrait plus d'informations je ne vois pas de problème de mon côté

**Comment by DOMNA13** [comment]
Au moment de la recherche du repo du V4 pour l'installer, quand je clique dessus ca m'envoie sur une page avec " Unknown error "
Par contre Les autres repo fonctionnent parfaitement mais pas celui du V4.

**Comment by Aohzan** [comment]
hacs est à jour ?

**Comment by DOMNA13** [comment]
![UE IPX-V4](https://user-images.githubusercontent.com/113241790/215102816-84563e7b-1e5f-46c5-bb9e-85feecf493cf.png)
Oui Hacs est sur la dernière màj
![Uploading UE IPX-V4.png…]()

**Comment by Aohzan** [comment]
Il n'y a pas plus d'info dans les logs ? Peut etre essayer de réinstaller HACS ?

**Comment by DOMNA13** [comment]
Ca fonctionne!!
Merci énormément Matthieu.
