### ISSUE TITLE
Add value_template option

### ISSUE THREAD

**Issue by MacGeyer** [Aohzan/ipx800#39]
I need to use "analogin" or "virtualanalogin" type but I also need to add some calculations, could you add value_template option please or do you have another solution to map IPX800 sensor formulas to Home Assistant ?

**Comment by Aohzan** [comment]
Hello,
You should use template entities https://www.home-assistant.io/integrations/template/#state-based-template-binary-sensors-buttons-numbers-selects-and-sensors

**Comment by MacGeyer** [comment]
Yes a une this workaround currently :

ipx800v4:
  - name: IPX800
    host: "10.0.0.102"
    api_key: "apikey"
    devices:
      - component: binary_sensor
        name: Filtration Piscine
        type: digitalin
        icon: mdi:pump
        id: 1
      - name: RAW PH Piscine
        icon: mdi:water-boiler
        type: "virtualanalogin"
        component: "sensor"
        
        id: 29
      - name: RAW RedOx Piscine
        icon: mdi:water-boiler
        type: "virtualanalogin"
        component: "sensor"
        id: 30

template:
  - sensor:
      - name: "Calc PH Piscine"
        state: "{{ (((states.sensor.raw_ph_piscine.state) | float) / 100) | round(1) }}"
        unit_of_measurement: ""
      - name: "Calc RedOx Piscine"
        state: "{{ ((states.sensor.raw_redox_piscine.state) | int) - 2500 }}"
        unit_of_measurement: mV

**Comment by Aohzan** [comment]
No because it's better to you use official template entities like you do, raw value in ipx800v4 integration, calculated value in template, as you will get all supported functions and filters, and nothing to maintain on my side.
I don't see what is the "existing formulas" ?

**Comment by Aohzan** [comment]
ahhh indeed I don't understand why GCE doesn't return the real value :thinking: 
maybe you can ask them ?
