### ISSUE TITLE
TC100 Sensor

### ISSUE THREAD

**Issue by Gilles-Clemenceau** [Aohzan/ipx800#42]
Hello,
J'essaie de passer sur cette intégration & je n'arrive pas à faire passer mon entrée analogique qui est branchée sur un TC100 :

```
      - name: IPX800 Température Piscine
        unit_of_measurement: '°C'
        device_class:  "temperature"
        type: "analogin"
        component: "sensor"
        id: 1
```

![image](https://github.com/Aohzan/ipx800/assets/3541681/efb3c48d-c3ae-4567-ac6a-695468bed5cd)

Je suis toujours en unavailable sur Home Assistant. :-/

**Comment by Aohzan** [comment]
hello
la config a l'air bonne pourtant :thinking: 
tu peux renvoyer le retour d'un appel de `Get=all` sur l'API ?

**Comment by Gilles-Clemenceau** [comment]
[xdevices.csv](https://github.com/Aohzan/ipx800/files/12428580/xdevices.csv)

Je l'ai mis en .csv mais c'est un json.
Effectivement, j'ai l'impression qu'il n'est pas présent.

![image](https://github.com/Aohzan/ipx800/assets/3541681/c58bdf21-5f0d-4f10-9e5a-35629c0063d2)

**Comment by Aohzan** [comment]
A1 n'existe pas, l'IPX ne renvoie aucune valeur analogique, le firmware est bien à jour ?

**Comment by Aohzan** [comment]
un `Get=A` renvoie quoi ?

**Comment by Gilles-Clemenceau** [comment]
Purée, mon firmware n'étais pas à jour effectivement... là j'ai bien ma valeur, tout marche parfaitement !
