### ISSUE TITLE
Push from 2 differents IPX

### ISSUE THREAD

**Issue by cjacquet92** [Aohzan/ipx800#43]
Having 2 IPX v4 in the network, in the same subnet as the home assistant.
IPX Pushes are not working since addition of API auth controls.
I don't know why but the script __init__ always take the 2nd IP of the IPX so request.remote is alway different of host and raise "API call not coming from IPX800 IP".
Push works when commenting this control.
It would be nice if this can be fixed cause I cannont fixe it from my side.
Regards*
C.

**Comment by Aohzan** [comment]
Hello, indeed it was not designed for multiple ipx, I will ckeck that

**Comment by Aohzan** [comment]
hello, it asks a lot of time to change this implementation, I'm not sure I can do it for only one person asking :disappointed:

**Comment by Aohzan** [comment]
Handled in last version :tada:
