### ISSUE TITLE
valeur des entités remontées en string au lieu de number

### ISSUE THREAD

**Issue by juju-5** [Aohzan/ipx800#44]
Les entitées remontées dans HA sont de type string. 

Serait-il possible que ce soit directement des number afin de pouvoir effectuer des calculs directement avec?

**Comment by Aohzan** [comment]
Est-ce que c'est mieux en 3.5.0 ?

**Comment by Aohzan** [comment]
c'est quelle entité (xthl, analogin...) ?
comment tu utilises la valeur ?
