### ISSUE TITLE
Push vers HA

### ISSUE THREAD

**Issue by matnoublanche** [Aohzan/ipx800#45]
Bonjour,

Après avoir cherché dans la doc et dans le code source, je n'arrive pas à trouver comment faire un toggle sur un groupe de lumières.

J'ai tenté d'appeler cette URL mais cela ne fonctionne pas comme attendu : `/api/ipx800v4/light.chambre_parents/toggle`

Le principe est de pouvoir changer l'état toggle des lumières plutôt que du ON/OFF car l'IPX ne connait pas l'état des lumières à l'avance, et je voudrais éviter les envois de type ON alors que la lumière est déjà sur ON sur HA.

Merci bien !

Mathieu

**Comment by matnoublanche** [comment]
Bonjour @LHommeQuAVuLOurs 

Oui c'est exactement ça, quand j'appuie sur un digital input de mon IPX, je veux déclencher un PUSH qui va toggle une lumière qui n'est pas sur un relais de l'IPX mais qui est sur le pont Hue.

Comme le pont n'est pas compatible directement avec la V4, je voudrais passer par HASS pour déclencher le toggle en passant par l'API spécifique du plugin.

Bonne journée.

**Comment by matnoublanche** [comment]
Ok merci pour ton retour.

Ma frayeur de procéder de la sorte c'est que ce n'est pas l'IPX qui pousse l'état directement sur HA mais plutôt HA qui tire l'update de l'IPX, puis qu'après ça selon le changement d'état le trigger se déclenche. Du coup cela veut dire que tu perds en réactivité entre le moment où tu appuies sur l'interrupteur et le moment où le trigger se déclenche.

J'imagine que tu as mis la fréquence des mise à jour toutes les secondes ou 2 secondes ?

Sinon en parallèle je suis en train de regarder comment faire avec des requêtes TCP que je catche sur NodeRed.

J'aurais pu me servir de l'API de HA, mais le problème c'est que sur l'IPX V4 tu ne peux pas faire de requêtes HTTP complexes.

**Comment by matnoublanche** [comment]
Ok merci à toi, je vais tenter tel quel pour voir si niveau réactivité cela correspond bien à ce que j'ai en ce moment avec Jeedom.

Bonne journée.

**Comment by matnoublanche** [comment]
Hello,

Bon en fait ça ne va pas de cette manière.

J'explique le problème.

Les digitaux sont tous des boutons poussoirs.

Quand on appuie sur le BP, un PUSH est envoyé vers HA lui demandant de faire un GET. Le temps que HA fasse le GET, quand il contrôle l'état du BP, on a déjà enlevé le doigt de celui-ci, il garde donc l'état éteint.

Pour que ça fonctionne, il faut rester appuyé plus d'une seconde sur le BP pour que HA aie le temps de comprendre que l'état est appuyé. Ce qui fait donc qu'on loupe l'état de cette manière.

Ou alors il faut qu'à la main, je fasse un push manuel vers chaque entité de HA, ce qui n'est pas pratique.

@Aohzan : Du coup je re-demande si c'est possible de faire un toggle sur une lumière en direct ?

Merci de ton retour.
Bonne journée.

**Comment by linkweaver** [comment]
Merci à tous les deux pour vos éclaircissements.

J'ai trouvé une solution qui me permet de couvrir mon besoin, que je détaille ici.

1/ On crée le PUSH dans l'IPX

<img width="906" alt="Capture d’écran 2023-11-13 à 21 25 26" src="https://github.com/Aohzan/ipx800/assets/85936156/f9a172c6-0799-42c3-aaad-63fd93dc768b">


2/ On crée une scène en ON/OFF selon l'entrée digitale qui va bien faire le PUSH

<img width="900" alt="Capture d’écran 2023-11-13 à 21 26 09" src="https://github.com/Aohzan/ipx800/assets/85936156/2d3fe7bf-e4f3-4da5-98a4-01ef9d96ac6b">


3/ Dans HA, on fait l'automatisation qui va faire le toggle.

<img width="1132" alt="Capture d’écran 2023-11-13 à 21 29 43" src="https://github.com/Aohzan/ipx800/assets/85936156/3be2fd9f-cdec-47c2-aeec-a293a72de442">


Ça fait faire un PUSH et une scène par bouton dans l'IPX, mais côté réactivité c'est plus rapide et plus fiable que de faire un PUSH qui fait un GET dans HA. Ça laisse aussi entrevoir des possibilité comme le fait de gérer les appuis longs dans HA, et ça c'est cool.

Bonne soirée.

**Comment by matnoublanche** [comment]
Je close l'issue, je me suis trompé de compte (!)
