### ISSUE TITLE
Remove entity/device on the integration

### ISSUE THREAD

**Issue by S1M8N** [Aohzan/ipx800#54]
Hello,

The problem come when I remove the entity in my configuration.yaml file, the entity/device stay in my home assistant integration.

I want to remove old entity in my integration. You think it's possible to add that ?

It's mandatory for me to disable the entity but it's not properly...

![image](https://github.com/Aohzan/ipx800/assets/75216525/e8322837-c665-4bf3-959b-9ef39d05196c)

**Comment by Aohzan** [comment]
Hello
This is related to HA functioning, I don't track existing entities of last start, so I can't delete them (as I can be an error and will be recreated at the next start), so the entity have to be deleted manually.
For the device, I don't know why HA doesn't delete empty device automatically, I didn't find a solution to do it in the integration, so the only way I found for now is to manually edit the `.storage/core.device_registry` file...
