### ISSUE TITLE
Would you clarify how to remove the IPX800 integration ?

### ISSUE THREAD

**Issue by ms83001** [Aohzan/ipx800#57]
Hello,

**Problem description**
As my home assistant is remote at 1000km, I'd like to be sure not to male any mistake when removing the IPX800 integration.
 
**Describe the solution you'd like**
I was expecting that just removing ipx800v4 from my configuration.yaml would make all associated entities disappeared.
But they are still present in "unavailable state".
What would "request for removal" trigger ? Is it safe wrt to may be subpackages used by IPX800 and some other inegration ? 

**Describe alternatives you've considered**
May be reactivating IPX800 integration and first remove all but one devices ?
Anyway I doubt because some old entities names are still present after I renamed them to new name.

**Additional context**
I discovered this IPX800V4 integration by google, when looking for IPX800 HTTP API I already used in the past for exchanges between IPX and Jeedom. IPX800 Integration is appealing at first glance, but I somewhat failed being undercontrol when something was going wrong in the communication (probably my mistakes in path/password/userid).
So I moved back to HTTP API, by the way using just extending usage of Node Red and MQTT broker I already have in place.

Thank you for your support

Michel

**Comment by Aohzan** [comment]
Hello
It's a HA mechanism, you have to delete manually the integration in the UI after removing it from YAML configuration
