### ISSUE TITLE
Invert_value ne fonctionne plus en 3.8.2

### ISSUE THREAD

**Issue by pvodoz** [Aohzan/ipx800#58]
Depuis le passage en 3.8.2, la configuration suivante ne fonctionne plus alors qu'elle ne posait pas de problème en 3.8.1:
![Screenshot_20240930_072809_Home Assistant](https://github.com/user-attachments/assets/e054a27b-6a6f-4e2b-a2cf-783c58bce3e5)

Voici le message d'erreur à la vérification du yaml:
![Screenshot_20240930_073240_Home Assistant](https://github.com/user-attachments/assets/c85cbc5c-dd19-43ce-b40b-cb91d2d6452d)

Ma version HA:
![Screenshot_20240930_073105_Home Assistant](https://github.com/user-attachments/assets/cd8a845e-8762-441b-b756-dc3236c44d76)

**Comment by Aohzan** [comment]
en effet je me suis loupé, est-ce que c'est mieux en 3.8.3 ?

**Comment by pvodoz** [comment]
Oui c'est corrigé!
Merci pour ta réactivité et pour tout le boulot sur IPX ;)
