### ISSUE TITLE
x4fp module should be declared as a select and not a climate.

### ISSUE THREAD

**Issue by Kolia56** [Aohzan/ipx800#61]
Currently, the x4fp module creates a climate entity which is not the best in my point of view because it is not thermostat, just 6 running modes. As a consequence, the gui displays a thermostat without temperature setting point and current temperature.

It would more appropriate I think to create a select entity with 6 options which are the 6 modes available with fils pilotes. As a workaround an option could be added in the configuration file in order to choose between climate or select.

Thank you

**Comment by Aohzan** [comment]
hello,
climate entities in HA handle no temperature as many other integrations, so it's the right way to use it, as it manage global states among other things
you can use a template climate over it to include an external temperature sensor entity
