### ISSUE TITLE
Optimisation retour API

### ISSUE THREAD

**Issue by bennijamm** [Aohzan/ipx800#8]
Bonjour,
Je viens de mettre en place ton extension sur HA, merci pour ce travail, cela fonctionne très bien.
Cependant, je pense qu'il y aurait une optimisation à faire côté API.
J'ai vu dans les logs que tu utilisais un Get=all.
Dans mon cas, j'ai beaucoup de modules GCE et donc beaucoup d'entrées, de sorties, de relay... bref, ça ramène beaucoup de choses par rapport à ce que j'utilise réellement.

Dans Jeedom que j'utilisais jusqu'à présent, on cochait ce qu'on voulait rapporter :
[All] Tous 
[A] Entrée analogique 
[C] Compteurs 
[R] Sortie digital (relai) 
[D] Entrès digital 
[VI] Entrée virtuel 
[VO] Sortie virtuel 
[VA] Entrée analogique virtuelle 
[PW] Watchdog 
[XTHL] Sonde THL 
[VR] Volet roulant 
[XENO] EnOcean 
[FP] Fil pilote 
[G] X-Dimmer 
[T] Thermostat 
[XPWM] PWM 
[X010V] 010V

Si c'est possible, dans les paramètres de l'extension de sélectionner uniquement ce qu'on utilise... ça pourrait être top !
Merci.

PS : je voulais modifier le readme pour compléter quelques infos que j'aurais bien eu besoin quand j'ai fait mon install mais ça a créé un fork. Je ne sais pas comment faire pour être "contributeur" de ton projet. Merci.

**Comment by Aohzan** [comment]
Salut,

En fait je fais une seule requête get=all et ensuite chaque entité va récupérer sa valeur. Si on fait par type, ça fera d'autant plus de requête à chaque fois.

Pour le README, il faut fork en effet, faire la modif puis faire une PR avec mon repo. Sinon tu peux proposer les modifs ici
