### ISSUE TITLE
Change for api push

### ISSUE THREAD

**Issue by EtienneDeneuve** [Aohzan/ipx800#9]
Hello ! 

thanks for the work on HA and IPX800, very useful.

just a quick info, the way you push the API from HA, can be better to avoid multiple declaration in PUSH on the IPX.

they support some variables mentioned here [gce wiki push](http://gce.ovh/wiki/index.php?title=API_V4#Inclure_des_.C3.A9tiquettes_dans_les_notifications_.28mail.2C_push_et_GSM.29)

Do you think I can start a PR with some change around this ?

**Comment by Aohzan** [comment]
If I understand, it's an improvement for https://github.com/Aohzan/ipx800/blob/46f929ec522a87b8fbf64792b7517b6af275f204/custom_components/ipx800/__init__.py#L239 ?
To handle multiple entities in one push ?

**Comment by EtienneDeneuve** [comment]
yep exactly :)

if we change to follow the logic of IPX we can avoid multiple declaration and make it simpler.

**Comment by EtienneDeneuve** [comment]
I've not yet a "magic" url clear in mind but, worth to share and make it better \o/

**Comment by FredericNauleau** [comment]
Hello, 

Thank you for your excellent work. I've made a custom sensor to get the status.xml from the IPX but your component is quit better. I a m agree about the fact that it can be interesting on have a push on event on IPX that send all components states on each change. Better than polling every x secs.

**Comment by Aohzan** [comment]
I add it to the TODO list :+1:

**Comment by Aohzan** [comment]
Hello @FredericNauleau @EtienneDeneuve,
the feature is on the last dev version : https://github.com/Aohzan/ipx800/tree/dev
the README https://github.com/Aohzan/ipx800/blob/dev/README.fr.md#push-%C3%A9tat-depuis-lipx800

please read the CHANGELOG as there is changes before testing, and let me know if it's work for you
